apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-xtuq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-xtuq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-xtuq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-xtuq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-xtuq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qzxb-tenant/rhtap-demo-app/hacbs-test-project-xtuq@sha256:c1a6b7ffa6e63b194fe00ee58d24192f46378299958438bb2c2fd5b0b92a4da1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
